---
name: CI Pipeline


on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  matrix:
    strategy:
      matrix: [ubuntu-latest, macos-latest]

  steps:
  - uses: actions/checkout@v4
  - name: Execute tests
    run: make
